---
title: "Kincade_SL_spatial"
author: "Bryant Willoughby"
date: "2023-08-19"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(SuperLearner)
library(GpGp)
library(ggplot2)
library(caret)
```


Read in fulldata
```{r}
fulldata <- read_csv("C:/Users/Bryant Willoughby/Documents/DRUMS/raw(Kincade)/Final data sets/prefire_kincade_grouped_standard_finaldata.csv")
```

Read in training/test data 
```{r}
train <- read_csv("C:/Users/Bryant Willoughby/Documents/DRUMS/raw(Kincade)/intermediate/Kincade_traindata.csv")

test <- read_csv("C:/Users/Bryant Willoughby/Documents/DRUMS/raw(Kincade)/intermediate/Kincade_testdata.csv")
```

# Linear Regression (spatial covariance) Results

Fit model 
```{r}
#fit new meta-model to account for spatial autocorrelation
y <- train$dnbr
locs <- as.matrix(train[, c('Lon', 'Lat')])
X <- train[, !(names(train) %in% c('dnbr', 'Lat', 'Lon', 'LC'))]
new_column <- rep(1, nrow(X))
X <- cbind(new_column, X)

# using fit_model() function part of GpGp package to account for spatial correlation
fit <- fit_model(y = y, locs = locs, X = X, covfun_name = "exponential_isotropic", silent = T)

```

make predictions on the testing set using SuperLearner
```{r}
s <- as.matrix(test[, c('Lon', 'Lat')])
preds <- test[, !(names(test) %in% c('dnbr', 'Lat', 'Lon', 'LC'))]
new_col <- rep(1, nrow(preds))
preds <- cbind(new_col, preds)

# Generate predictions
predictions <- predictions(fit, locs_pred = s, X_pred = preds)

```

# RMSE calculation
```{r}
source("C:/Users/Bryant Willoughby/Documents/DRUMS/code/week a/RMSE_function.R")
actual <- test$dnbr
predicted <- predictions

val_RMSE <- RMSE(actual, predicted)
val_RMSE <- round(val_RMSE, 0)
val_RMSE
```

# Confusion Matrix

Create summary table for confusion matrix computation
```{r}
data <- test[2:4] %>%
  mutate("dnbr_class" = if_else(dnbr >= 660, 7, 
                                if_else(dnbr >= 440, 6, 
                                if_else(dnbr >= 270, 5,
                                if_else(dnbr >= 100, 4,
                                if_else(dnbr >= -100, 3, 
                                if_else(dnbr >= -250, 2, 1)))))), 
         "dnbr_preds" = predictions, 
         "dnbr_preds_class" = if_else(predictions >= 660, 7, 
                                if_else(predictions >= 440, 6, 
                                if_else(predictions >= 270, 5,
                                if_else(predictions >= 100, 4,
                                if_else(predictions >= -100, 3, 
                                if_else(predictions >= -250, 2, 1)))))))

```


```{r}
#Creates vectors having data points
expected_val <- factor(data$dnbr_class)
predicted_val <- factor(data$dnbr_preds_class)

#Creating confusion matrix
confusion_mat <- confusionMatrix(data=predicted_val, reference = expected_val)

confusion_mat
  #note: Accuracy = number of correct predictions / total number of predictions
```

Classification accuracy (CA)
```{r}
CA <- confusion_mat$overall[[1]]
CA <- round(CA, 3)
CA <- CA*100
CA
```

Classification accuracy high (CA-high)
```{r}
CA_high <- confusion_mat$table[7,7] / sum(confusion_mat$table[,7])
CA_high <- round(CA_high, 4)
CA_high <- CA_high*100
CA_high
```









