---
title: "fire_combo_grouping"
author: "Bryant Willoughby"
date: "2023-09-27"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
library(readr)
library(ggplot2)
```

Read in relevant files 
```{r}
KNP <- read_csv("C:/Users/Bryant Willoughby/Documents/DRUMS/raw(KNP)/Final data sets/prefire_knp_blr_grouped_finaldata.csv")

Windy <- read_csv("C:/Users/Bryant Willoughby/Documents/DRUMS/raw(Windy)/Final data sets/prefire_windy_grouped_finaldata.csv")

CZU <- read_csv("C:/Users/Bryant Willoughby/Documents/DRUMS/raw(CZU)/Final data sets/prefire_czu_grouped_finaldata.csv")

Kincade <- read_csv("C:/Users/Bryant Willoughby/Documents/DRUMS/raw(Kincade)/Final data sets/prefire_kincade_grouped_finaldata.csv")

```

# Standardize data

Combine and move LC first
```{r}
combined <- rbind(KNP, Windy, CZU, Kincade)
combined <- combined %>%
  select("LC", everything())
```

```{r}
# Display the original dataframe
print("Original dataframe:")
print(combined)

# Columns to exclude from standardization
columns_to_exclude <- c("LC", "Lat", "Lon", "dnbr", "dnbr6")

# Standardize all columns except the ones to exclude
columns_to_standardize <- setdiff(names(combined), columns_to_exclude)
combined[columns_to_standardize] <- scale(combined[columns_to_standardize], 
                                          center = T, scale = T)

# Display the dataframe after standardization
print("Dataframe after standardization:")
print(combined)
```

```{r}
#write.csv(combined, "C:/Users/Bryant Willoughby/Documents/DRUMS/raw(combined)/combined_standardized.csv", row.names=F)
```
